@startuml casodeuso
left to right direction
skinparam monochrome true

actor Usuário
actor Administrador
actor SistemaPagBank

rectangle Bot {
  usecase "Iniciar processo de doação" as UC1
  usecase "Escolher forma de pagamento" as UC2
  usecase "Gerar QR Code PIX" as UC3
  usecase "Visualizar link PayPal" as UC4
  usecase "Aprovar doação" as UC6
  usecase "Visualizar painel admin" as UC7
}

Usuário --> UC1
Usuário --> UC2
UC2 --> UC3 : PIX selecionado
UC2 --> UC4 : Cartão selecionado
SistemaPagBank --> UC3 : Retorna QR Code

Administrador --> UC6
Administrador --> UC7

UC3 .> SistemaPagBank : API call
@enduml